FROM ubuntu:bionic

WORKDIR /app

RUN apt-get update && \
    apt-get install -y --no-install-recommends libcurl4-openssl-dev python3-pip libboost-python-dev libpython3-dev python3-setuptools && \
    rm -rf /var/lib/apt/lists/* 

RUN pip3 install --upgrade pip
RUN pip install setuptools
RUN pip install ptvsd==4.1.3
COPY . .
RUN pip install -e ./azure-iot-sdk-python-preview/azure-iot-device

RUN useradd -ms /bin/bash moduleuser
USER moduleuser

CMD [ "python3", "-u", "./main.py" ]
